require("core.plugin_config.gruvbox")
require("core.plugin_config.lualine")
require("core.plugin_config.nvimtree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.lsp_config")
require("core.plugin_config.completion")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.gitsigns")
require("core.plugin_config.debug")
require("core.plugin_config.highlight")
require("core.plugin_config.autopairs")
require("core.plugin_config.tabline")
-- require("core.plugin_config.bufferline")
-- require("core.plugin_config.vimux")
