shell:
  program: ubuntu2204.exe

env:
  TERM: xterm-256color

font:
  normal:
    family: "JetBrainsMono Nerd Font Mono"
    style: Medium
  bold:
    family: "JetBrainsMono Nerd Font Mono"
    style: Bold
  italic:
    family: "JetBrainsMono Nerd Font Mono"
    style: Italic
  bold_italic:
    family: "JetBrainsMono Nerd Font Mono"
    style: Bold Italic
  size: 13
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

window:
  opacity: 1
  #position:
  #  x: 14
  #  y: 14
  #dimensions:
  #  columns: 171
  #  lines: 38
  padding:
    x: 5
    y: 5

  # Startup Mode (changes require restart)
  # Available option: Windowed | Maximized | Fullscreen (must turn comment off position and dimension to have effect)
  startup_mode: Windowed
  # Available values:
  # - full, none, transparent, buttonless
  decorations: full
  
import:
  - C:\Users\dn200\AppData\Roaming\alacritty\themes\gruvbox.yml

transparent_background_colors: true

custom_cursor_colors: true

cursor:
  style:
    # Values for `shape`: ▇ Block; _ Underline; | Beam
    shape: Beam
      # Cursor blinking state
      # Values for `blinking`:
      #   - Never: Prevent the cursor from ever blinking
      #   - Off: Disable blinking by default
      #   - On: Enable blinking by default
      #   - Always: Force the cursor to always blink
    blinking: Always

      # Cursor blinking interval in milliseconds.

      # Time after which cursor ss blinking, in seconds.
      # Specifying '0' will disable timeout for blinking.

      # If this is `true`, the cursor will be rendered as a hollow box when the
      # window is not focused.
    unfocused_hollow: true

      # Thickness of the cursor relative to the cell width as floating point number
    draw_bold_text_with_bright_colors: true

    live_config_reload: true

    scrolling:
      history: 10000
    multiplier: 10


key_bindings:
  - { key: V,        mods: Control|Shift, mode: ~Vi ,action: Paste }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: N,        mods: Control|Shift, action: SpawnNewInstance }
  - { key: Q,        mods: Alt,           action: Quit             }
  - { key: Return,   mods: Alt,           action: ToggleFullscreen }
  - { key: Plus,     mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }

mouse:
  # Click settings
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
    # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

  selection:
    semantic_escape_chars: ",│`|:\"' ()[]{}<>"
      # When set to `true`, selected text will be copied to the primary clipboard.
    save_to_clipboard: true
