colors:
  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xd3c6aa'
    cursor: '0x7a8478'
  vi_mode_cursor:
    text: '0x272e33'
    cursor: '0xd3c6aa'
  primary:
    background: '0x1e2326'
    foreground: '0xd3c6aa'
      # Normal colors
  normal:
    black:   '0x374145'
    red:     '0xe67e80'
    green:   '0xa7c080'
    yellow:  '0xdbbc7f'
    blue:    '0x7fbbb3'
    magenta: '0xd699b6'
    cyan:    '0x83c092'
    white:   '0xd3c6aa'
    # Bright colors
  bright:
    black:   '0x374145'
    red:     '0xe67e80'
    green:   '0xa7c080'
    yellow:  '0xe69875'
    blue:    '0x7fbbb3'
    magenta: '0xd699b6'
    cyan:    '0x83c092'
