set -g escape-time 0
set -g mouse on
set -g base-index 1
setw -g prefix C-s

set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

# split pane vertically with prefix -
bind-key - split-window -v
# split pane horizontally with prefix _
bind-key _ split-window -h

#act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

unbind r

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'olimorris/tmux-pomodoro-plus'

# status bar config
set-option -g status-position top
## COLORSCHEME: gruvbox dark (medium)
set-option -g status "on"


# default window with an activity alert
set-window-option -g window-status-activity-style bg=color237,fg=color248 # bg=bg1, fg=fg3
# active window title colors
set-window-option -g window-status-current-style bg=red,fg=color237 # fg=bg1
# pane border
set-option -g pane-active-border-style fg=color250 #fg2
set-option -g pane-border-style fg=color237 #bg1
# message infos (command line style)
set-option -g message-style bg=color108,fg=color235,bold # bg=bg2, fg=fg1
# writing commands inactive
set-option -g message-command-style bg=color235,fg=color223,bold # bg=fg3, fg=bg1
# pane number display
set-option -g display-panes-active-color color250 #fg2
set-option -g display-panes-color color237 #bg1
# clock
set-window-option -g clock-mode-color color108 #blue

# bell
set-window-option -g window-status-bell-style bg=color167,fg=color235 # bg=red, fg=bg

## Theme settings mixed with colors (unfortunately, but there is no cleaner way)
# Variables for status bar
st_left1="#[fg=color235,bold]#{?client_prefix,#[bg=color108] 待 ,#[bg=color109] 春 }#[bg=color235]#{?client_prefix,#[fg=color108],#[fg=color109]}"
st_left2="#[bold]#{?client_prefix,#[fg=color246],#[fg=color246]}#(whoami)"
st_date="#[bg=color235,fg=color246,bold]   %d-%m-%Y"
st_tmux_mcl="#[fg=color246,bold]#(tmux-mem-cpu-load -a 0 -m 1 -t 1 -g 0 -i 2)"

# {pane_current_path} -- for display current path in tmux
set -g @pomodoro_granularity 'on'
set -g @pomodoro_on "#[fg=color246]"
set -g @pomodoro_complete "#[fg=color109]"
set -g status-interval 1

set-option -g status-justify centre
# set-option -g status-left-style none
# set-option -g status-right-style none
set-option -g status-left-length "80"
set-option -g status-right-length "80"
set-window-option -g window-status-separator " #[fg=color239]| "

# Default status and window color
set-option -g status-style "#{?client_prefix,bg=color235,bg=color235},fg=color223" # bg=bg1, fg=fg1
set-window-option -g window-status-style bg=color235,fg=color246 #bg=#282828 ,fg=#a89984

set-option -g status-left "${st_left1} ${st_tmux_mcl} "
set-option -g status-right "#[bold]#{pomodoro_status}${st_date} #[bg=color235]#{?client_prefix,#[fg=color108],#[fg=color109]}#{?client_prefix,#[bg=color108],#[bg=color109]}#[fg=color235,bold] #S "

# Window styling config
set-window-option -g window-status-current-format
"#[bg=color235,bold,italics]#{?client_prefix,#[fg=color108],#[fg=color109]}#I: #[bg=color235,fg=color246,bold,noitalics] #W#{?window_zoomed_flag,*Z,}"
set-window-option -g window-status-format "#[bg=color235,fg=color239,bold,italics]#I#[bold,noitalics]: #W"

# vim: set ft=tmux tw=0 nowrap:

# Automatic tpm installation on new machine/setup
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
