set-option -g default-terminal "screen-256color"
set -ag terminal-overrides ",screen-256color:RGB"

set -g escape-time 0
set-option -g prefix C-s

# split pane vertically with prefix -
bind-key - split-window -v
# split pane horizontally with prefix _
bind-key _ split-window -h

#act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# status bar config
set-option -g status-interval 1
set-option -g status-keys vi
set-option -g status-position top

## COLORSCHEME: gruvbox dark (medium)
set-option -g status "on"

# default statusbar color
set-option -g status-style bg=colour237,fg=colour223 # bg=bg1, fg=fg1

# default window title colors
set-window-option -g window-status-style bg=colour214,fg=colour237 # bg=yellow, fg=bg1

# default window with an activity alert
set-window-option -g window-status-activity-style bg=colour237,fg=colour248 # bg=bg1, fg=fg3

# active window title colors
set-window-option -g window-status-current-style bg=red,fg=colour237 # fg=bg1

# pane border
set-option -g pane-active-border-style fg=colour250 #fg2
set-option -g pane-border-style fg=colour237 #bg1

# message infos
set-option -g message-style bg=colour239,fg=colour223 # bg=bg2, fg=fg1

# writing commands inactive
set-option -g message-command-style bg=colour239,fg=colour223 # bg=fg3, fg=bg1

# pane number display
set-option -g display-panes-active-colour colour250 #fg2
set-option -g display-panes-colour colour237 #bg1

# clock
set-window-option -g clock-mode-colour colour109 #blue

# bell
set-window-option -g window-status-bell-style bg=colour167,fg=colour235 # bg=red, fg=bg

## Theme settings mixed with colors (unfortunately, but there is no cleaner way)
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""
set-option -g status-left "#[bg=colour202,fg=colour237,bold] #S #[bg=colour208,fg=colour202,nobold,noitalics,nounderscore] #[bg=colour208,fg=colour237,bold,noitalics]#{pane_current_path} #[bg=colour237,fg=colour208,nobold,noitalics,nounderscore]"
set-option -g status-right "#[bg=colour237,fg=colour239 nobold, nounderscore, noitalics]#[bg=colour239,fg=colour246] %Y-%m-%d  %H:%M #[bg=colour239,fg=colour208,nobold,noitalics,nounderscore]#[bg=colour208,fg=colour237] #h "

set-window-option -g window-status-current-format "#[bg=colour108,fg=colour237,nobold,noitalics,nounderscore]#[bg=colour108,fg=colour237,bold] #I #[bg=colour108,fg=colour237,bold] #W#{?window_zoomed_flag,*Z,} #[bg=colour237,fg=colour108,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=colour239,fg=colour237,noitalics]#[bg=colour239,fg=colour223] #I #[bg=colour239,fg=colour223] #W #[bg=colour237,fg=colour239,noitalics]"

# vim: set ft=tmux tw=0 nowrap:


# powerline colors
set-option -g status-style bg=color237,fg=white
set-option -g window-status-current-style fg=yellow,bg=color235
set-option -g window-status-style fg=white,bg=black
set-option -g pane-border-style fg=green
set-option -g pane-active-border-style fg=yellow

# Automatic tpm installation on new machine/setup
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
