# Main Colors
unrecognized_file: white
recognized_file:   cyan
executable_file:   magenta
dir:               green

# Link
dead_link: red
link:      cyan

# special files
socket:    green
blockdev:  green
chardev:   green

# Access Modes
write:     yellow
read:      red
exec:      green
no_access: red

# Age
day_old:     white
hour_old:    white
no_modifier: white

# File Size
file_large:  orange
file_medium: gold
file_small:  white

# Random
report: white
user:   white
tree:   white
empty:  white
error:  white
normal: white
inode:  white

# Git
addition:     chartreuse
modification: darkkhaki
deletion:     darkred
untracked:    darkorange
unchanged:    forestgreen
