colors:
  primary:
    background: "#181825"
    foreground: "#cdd6f4"
  cursor:
    text:   "#cdd6f4"
    cursor: "#585b70"
  vi_mode_cursor:
    text:   "#cdd6f4"
    cursor: "#585b70"
  line_indicator:
    foreground: None
    background: None
  selection:
    text:       "#cdd6f4"
    background: "#585b70"
  normal:
    black:      "#1e1e2e"
    red:        "#f38ba8"
    green:      "#a6e3a1"
    yellow:     "#f9e2af"
    blue:       "#89b4fa"
    magenta:    "#cba6f7"
    cyan:       "#94e2d5"
    white:      "#e0def4"
  bright:
    black:      "#6e6a86"
    red:        "#eb6f92"
    green:      "#31748f"
    yellow:     "#f6c177"
    blue:       "#9ccfd8"
    magenta:    "#c4a7e7"
    cyan:       "#ebbcba"
    white:      "#cdd6f4"
  hints:
    start:
      foreground: "#908caa"
      background: "#1e1e2e"
    end:
      background: "#1e1e2e" 
      foreground: "#6e6a86"
