[colors.primary]
background = "#1e2326"
foreground = "#d3c6aa"

[colors.normal]
black   = "#374145"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"

[colors.bright]
black   = "#374145"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#e69875"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"

[colors.vi_mode_cursor]
text    = "#1e2326"
cursor  = "#d3c6aa"

[colors.cursor]
text    = "#d3c6aa"
cursor  = "#7a8478"
