[colors.primary]
background = "#1b1b1b"
foreground = "#d5c4a1"

[colors.normal]
black   = "#45403d"
red     = "#e67e80"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#d5c4a1"

[colors.bright]
black   = "#282828"
red     = "#fe8019"
green   = "#b8bb26"
yellow  = "#f28534"
blue    = "#bdae93"
magenta = "#d5c4a1"
cyan    = "#d65d0e"
white   = "#d5c4a1"

[colors.vi_mode_cursor]
cursor  = "#d5c4a1"
text    = "#282828"

[colors.cursor]
cursor  = "#d5c4a1"
text    = "#282828"
