colors:
  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text:     '#1d2021'
    cursor:   '#d5c4a1'
  vi_mode_cursor:
    text:     '#1d2021'
    cursor:   '#d5c4a1'
  primary:
    background: '#141617'
    foreground: '#d5c4a1'
      # Normal colors
  normal:
    black:   '#595d5f'
    red:     '#e67e80'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#8bc1ad'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#d5c4a1'
    # Bright colors
  bright:
    black:   '#323435'
    red:     '#fe8019'
    green:   '#3c3836'
    yellow:  '#f28534'
    blue:    '#bdae93'
    magenta: '#ebdbb2'
    cyan:    '#d65d0e'
