#!/usr/bin/env zsh

source $HOME/.config/sketchybar/theme.sh

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
  height=36 \
  blur_radius=30 \
  color=0x661b1b1b \
  margin=0 \
  sticky=on \
  padding_left=23 \
  padding_right=23 \
  notch_width=188 \
  display=main

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a
default=( 
  background.color=0xff282828
  background.corner_radius=5
  background.padding_right=5
  # background.border_color=$FG
  # background.border_width=1
  background.height=26
  icon.font="$FONT_FACE:EXTRABOLD:17.0"
  icon.padding_left=5
  icon.padding_right=5
  label.font="$FONT_FACE:EXTRABOLD:14.0"
  label.color=0xffd5c4a1
  label.y_offset=0
  label.padding_left=0
  label.padding_right=5
)

sketchybar --default "${default[@]}"

sketchybar \
  --add item Logo left \
  --set Logo \
  background.color=0xff8ec07c \
  icon.color=0xff282828 \
  icon.y_offset=1 \
  label.drawing=off \
  script="$PLUGIN_SHARED_DIR/Logo.sh" \
  --subscribe Logo mouse.clicked

sketchybar --add item front_app left \
  --set front_app \
  background.color=0xff45403d\
  background.padding_left=0 \
  background.padding_right=0 \
  icon.y_offset=1 \
  icon.color=$FG \
  label.drawing=no \
  script="$PLUGIN_SHARED_DIR/front_app.sh" \
  --add item front_app.separator left \
  --set front_app.separator \
  background.color=0x00000000 \
  background.padding_left=-3 \
  icon= \
  icon.color=0xff45403d \
  icon.font="$FONT_FACE:EXTRABOLD:20.0" \
  icon.padding_left=0 \
  icon.padding_right=0 \
  icon.y_offset=1 \
  label.drawing=no \
  label.y_offset=2 \
  --add item front_app.name left \
  --set front_app.name \
  background.color=0x00000000 \
  background.padding_right=0 \
  icon.drawing=off \
  label.font="$FONT_FACE:EXTRABOLD:14.0" \
  label.drawing=yes \
  label.y_offset=1 \
  --subscribe front_app front_app_switched

# SPACE_ICONS=("1" "2" "3")
# for i in "${!SPACE_ICONS[@]}"
# do
#   sid="$(($i+1))"
#   space=(
#     space="$sid"
#     icon="${SPACE_ICONS[i]}"
#     icon.padding_left=7
#     icon.padding_right=7
#     background.color=0x40ffffff
#     background.corner_radius=5
#     background.height=25
#     label.drawing=off
#     script="$PLUGIN_SHARED_DIR/space.sh"
#     click_script="yabai -m space --focus $sid"
#   )
#   sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
# done

sketchybar \
  --add item current_space left \
  --set current_space \
  background.padding_left=4 \
  background.color=0xff282828 \
  icon.color=0xffd5c4a1 \
  label.drawing=off \
  script="$PLUGIN_SHARED_DIR/current_space.sh" \
  --subscribe current_space space_change

sketchybar --add item weather.moon q \
  --set weather.moon \
  background.color=$BLACK_1 \
  background.padding_right=-1 \
  icon.color=$FG \
  icon.font="$FONT_FACE:Bold:22.0" \
  icon.padding_left=4 \
  icon.padding_right=3 \
  label.drawing=off \
  --subscribe weather.moon mouse.clicked

sketchybar --add item weather q \
  --set weather \
  icon= \
  icon.color=0xfff5bde6 \
  icon.font="$FONT_FACE:Bold:15.0" \
  update_freq=1800 \
  script="$PLUGIN_SHARED_DIR/weather.sh" \
  --subscribe weather system_woke

sketchybar \
  --add item yabai_layout e \
  --set yabai_layout \
  background.color=$BLACK_1 \
  icon.color=$FG \
  icon.y_offset=1 \
  icon.font="$FONT_FACE:ExtraBold:16.0" \
  label.drawing=off \
  label.padding_left=3 \
  script="$PLUGIN_SHARED_DIR/yabai_layout.sh" \
  --subscribe yabai_layout mouse.clicked

sketchybar \
  --add event spotify_change $SPOTIFY_EVENT \
  --add item spotify e \
  --set spotify \
  icon= \
  icon.y_offset=1 \
  icon.font="$FONT_FACE:Bold:20.0" \
  label.drawing=off \
  label.padding_left=3 \
  script="$PLUGIN_DIR/spotify.sh" \
  --subscribe spotify spotify_change mouse.clicked

sketchybar --add bracket front_app_bracket \
  front_app \
  front_app.separator \
  front_app.name \
  --subscribe front_app front_app_switched

sketchybar --add item clock right \
  --set clock \
  icon=󰃰 \
  icon.color=0xffed8796 \
  update_freq=10 \
  script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add item battery right \
  --set battery \
  update_freq=10 \
  script="$PLUGIN_DIR/battery.sh"

sketchybar \
  --add item volume right \
  --set volume \
  icon.color=0xff8aadf4 \
  script="$PLUGIN_SHARED_DIR/volume.sh" \
  --subscribe volume volume_change

# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
