#!/usr/bin/env zsh

source $HOME/.config/sketchybar/theme.sh

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

sketchybar --bar          \
  color=0x001b1b1b        \
  border_color=0x00000000 \
  position=top            \
  height=42               \
  notch_display_height=0  \
  margin=0                \
  y_offset=0              \
  corner_radius=0         \
  border_width=0          \
  blur_radius=20          \
  padding_left=20         \
  padding_right=23        \
  notch_width=222         \
  notch_offset=0          \
  display=main            \
  hidden=off              \
  topmost=off             \
  sticky=on               \
  font_smoothing=off      \
  shadow=off

default=( 
  background.height=34
  background.color=$BLACK
  background.border_color=$BLACK_1
  background.border_width=0
  background.corner_radius=16
  background.drawing=off
  icon.font="$FONT_FACE:EXTRABOLD:17.0"
  icon.padding_left=10
  icon.padding_right=10
  label.font="$FONT_FACE:EXTRABOLD:14.0"
  label.color=$FG
  label.y_offset=0
)

sketchybar --default "${default[@]}"

# Left side =============================================================================
sketchybar \
  --add item Logo left \
  --set      Logo script="$PLUGIN_SHARED_DIR/Logo.sh" \
                  label.drawing=off \
                  icon.font="$FONT_FACE:EXTRABOLD:18.0" \
                  icon.color=$GREEN \
                  icon.y_offset=1 \
                  icon.padding_left=12 \
                  icon.padding_right=0 \
  --add item front_app left \
  --set      front_app script="$PLUGIN_SHARED_DIR/front_app.sh" \
                       background.color=none\
                       background.padding_left=4 \
                       background.padding_right=2 \
                       background.border_width=0 \
                       icon.y_offset=1 \
                       icon.color=$BLUE \
                       label.drawing=no \
  --add item front_app.name left \
  --set      front_app.name background.color=0x00000000 \
                            background.padding_right=0 \
                            background.padding_right=0 \
                            icon.drawing=off \
                            label.font="$FONT_FACE:EXTRABOLD:14.0" \
                            label.drawing=yes \
                            label.y_offset=1 \
  --add item current_space left \
  --set      current_space script="$PLUGIN_SHARED_DIR/current_space.sh" \
                           background.padding_left=4 \
                           icon.color=$YELLOW \
                           icon.padding_left=8 \
                           icon.padding_right=13 \
                           label.drawing=off \
  --add item weather.moon q \
  --set      weather.moon script="$PLUGIN_SHARED_DIR/weather.moon.sh" \
                          background.padding_right=-1 \
                          background.border_color=$ACCENT \
                          icon.color=$FG \
                          icon.font="$FONT_FACE:Bold:22.0" \
                          icon.padding_right=9 \
                          label.drawing=off \
  --add item weather.moon q \
  --set      weather.moon script="$PLUGIN_SHARED_DIR/weather.moon.sh" \
                          background.padding_right=-1 \
                          background.border_color=$ACCENT \
                          icon.color=$FG \
                          icon.font="$FONT_FACE:Bold:22.0" \
                          icon.padding_right=9 \
                          label.drawing=off \
  --add item weather q \
  --set      weather script="$PLUGIN_SHARED_DIR/weather.sh" \
                     icon= \
                     icon.color=$PURPLE \
                     icon.font="$FONT_FACE:Bold:15.0" \
                     update_freq=1800 \
  --add item empty q \
  --set      empty background.padding_right=100 \

# Right side ============================================================================
sketchybar \
  --add item yabai_layout e \
  --set      yabai_layout icon.color=$FG \
                          icon.y_offset=1 \
                          icon.font="$FONT_FACE:ExtraBold:16.0" \
                          label.drawing=off \
                          script="$PLUGIN_SHARED_DIR/yabai_layout.sh" \
  --add item empty_e_right e \
  --set      empty_e_right icon.padding_left=1 \
             empty_e_right icon.padding_right=1 \
  --add item spotify e \
  --set      spotify icon.y_offset=1 \
                     icon.font="$FONT_FACE:Bold:20.0" \
                     label.drawing=off \
                     script="$PLUGIN_DIR/spotify.sh" \
  --add item clock right \
  --set      clock script="$PLUGIN_SHARED_DIR/clock.sh" \
                   icon=󰃰 \
                   icon.color=$PURPLE \
                   update_freq=10 \
                   label.padding_right=10 \
  --add item battery right \
  --set      battery script="$PLUGIN_DIR/battery.sh" \
                     update_freq=10 \
                     icon.font="$FONT_FACE:Bold:18.0" \
  --add item volume right \
  --set      volume icon.color=$BLUE \
                     icon.font="$FONT_FACE:Bold:20.0" \
                     script="$PLUGIN_SHARED_DIR/volume.sh" \

# Brackets ==============================================================================
sketchybar \
  --add bracket left_bracket Logo front_app front_app.name current_space \
  --set         left_bracket background.color=0xcc000000 \
  --add bracket weather_bracket weather weather.moon \
  --set         weather_bracket background.color=0xcc000000 \
  --add bracket right_bracket clock battery volume spotify \
  --set         right_bracket background.color=0xcc000000 \
  --add bracket layout_bracket yabai_layout \
  --set         layout_bracket background.color=0xcc000000 \


# Events ================================================================================
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
sketchybar --add event spotify_change $SPOTIFY_EVENT \

sketchybar \
  --subscribe current_space     space_change \
  --subscribe front_app         front_app_switched \
  --subscribe weather.moon      mouse.entered mouse.exited mouse.clicked \
  --subscribe weather           mouse.entered mouse.exited mouse.clicked system_woke \
  --subscribe Logo              mouse.entered mouse.exited mouse.clicked \
  --subscribe yabai_layout      mouse.entered mouse.exited mouse.clicked \
  --subscribe spotify           mouse.entered mouse.exited mouse.clicked spotify_change \
  --subscribe volume            mouse.entered mouse.exited mouse.clicked volume_change \
  --subscribe clock             mouse.entered mouse.exited mouse.clicked \
 
# Finalizing Setup ======================================================================
sketchybar --update
sketchybar --trigger space_change
