#!/usr/bin/env zsh

source $HOME/.config/sketchybar/theme.sh

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
  height=42 \
  blur_radius=40 \
  color=0x001b1b1b \
  margin=0 \
  sticky=on \
  padding_left=23 \
  padding_right=23 \
  notch_width=222 \
  display=main

default=( 
  background.color=$BLACK
  background.corner_radius=16
  background.padding_right=5
  background.border_color=$GREY
  background.border_width=2
  background.height=34
  icon.font="$FONT_FACE:EXTRABOLD:17.0"
  icon.padding_left=10
  icon.padding_right=10
  label.font="$FONT_FACE:EXTRABOLD:14.0"
  label.color=$FG
  label.y_offset=0
  label.padding_left=0
  label.padding_right=10
)

sketchybar --default "${default[@]}"

sketchybar \
  --add item Logo left \
  --set Logo \
  background.color=$BLACK \
  label.drawing=off \
  script="$PLUGIN_SHARED_DIR/Logo.sh" \
  icon.font="$FONT_FACE:EXTRABOLD:18.0" \
  icon.color=$GREEN \
  icon.y_offset=1 \
  icon.padding_left=11 \
  --subscribe Logo mouse.entered mouse.exited mouse.clicked \
  \
  --add item front_app left \
  --set front_app \
  background.color=none\
  background.padding_left=4 \
  background.padding_right=2 \
  background.border_width=0 \
  icon.y_offset=1 \
  icon.color=$BLUE \
  label.drawing=no \
  script="$PLUGIN_SHARED_DIR/front_app.sh" \
  --add item front_app.name left \
  --set front_app.name \
  background.color=0x00000000 \
  background.padding_right=5 \
  background.border_width=0 \
  icon.drawing=off \
  label.font="$FONT_FACE:EXTRABOLD:14.0" \
  label.drawing=yes \
  label.y_offset=1 \
  --subscribe front_app front_app_switched \
  \
  --add item current_space left \
  --set current_space \
  background.padding_left=4 \
  background.color=$BLACK \
  icon.color=$YELLOW \
  icon.padding_left=12 \
  icon.padding_right=13 \
  label.drawing=off \
  script="$PLUGIN_SHARED_DIR/current_space.sh" \
  --subscribe current_space space_change \
  \
  --add item weather.moon q \
  --set weather.moon \
  background.color=$BLACK \
  background.padding_right=-1 \
  background.border_color=$ACCENT \
  icon.color=$FG \
  icon.font="$FONT_FACE:Bold:22.0" \
  icon.padding_right=9 \
  label.drawing=off \
  script="$PLUGIN_SHARED_DIR/weather.moon.sh" \
  --subscribe weather.moon mouse.entered mouse.exited mouse.clicked \
  \
  --add item weather q \
  --set weather \
  icon= \
  icon.color=$PURPLE \
  icon.font="$FONT_FACE:Bold:15.0" \
  update_freq=1800 \
  script="$PLUGIN_SHARED_DIR/weather.sh" \
  --subscribe weather system_woke mouse.entered mouse.exited mouse.clicked \
  \
  --add item yabai_layout e \
  --set yabai_layout \
  background.color=$BLACK \
  background.border_color=$ACCENT \
  icon.color=$FG \
  icon.y_offset=1 \
  icon.font="$FONT_FACE:ExtraBold:16.0" \
  label.drawing=off \
  script="$PLUGIN_SHARED_DIR/yabai_layout.sh" \
  --subscribe yabai_layout mouse.entered mouse.exited mouse.clicked \
  \
  --add event spotify_change $SPOTIFY_EVENT \
  --add item spotify e \
  --set spotify \
  icon.y_offset=1 \
  icon.font="$FONT_FACE:Bold:20.0" \
  label.drawing=off \
  script="$PLUGIN_DIR/spotify.sh" \
  --subscribe spotify spotify_change mouse.entered mouse.exited mouse.clicked \
  \
  --add bracket front_app_bracket \
  front_app \
  front_app.separator \
  front_app.name \
  --subscribe front_app front_app_switched \
  \
  --add item clock right \
  --set clock \
  icon=󰃰 \
  icon.color=$PURPLE \
  update_freq=10 \
  script="$PLUGIN_SHARED_DIR/clock.sh" \
  --subscribe clock mouse.entered mouse.exited mouse.clicked \
  \
  --add item battery right \
  --set battery \
  update_freq=10 \
  icon.font="$FONT_FACE:Bold:18.0" \
  script="$PLUGIN_DIR/battery.sh" \
  \
  --add item volume right \
  --set volume \
  icon.color=$BLUE \
  icon.font="$FONT_FACE:Bold:20.0" \
  script="$PLUGIN_SHARED_DIR/volume.sh" \
  --subscribe volume volume_change mouse.entered mouse.exited mouse.clicked

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
